<?php
declare(strict_types=1);

$this->headTitle('Meetups');

/** @var \App\Entity\Meetup[] $futureMeetups */
/** @var \App\Entity\Meetup[] $pastMeetups */
?>

</div><!-- end of gradient-wrapper -->

<?php
$first = true;
?>

<div class="wrapper content">
    <h1>Next Meetup<?php echo count($futureMeetups) > 1 ? 's' : ''; ?>...</h1>

    <?php if (count($futureMeetups) > 0): ?>
        <?php foreach ($futureMeetups as $meetup): ?>
            <?php
            if ($first) {
                echo $this->partial('layout::single-meetup-full', ['meetup' => $meetup]);
                $first = false;
                if (count($futureMeetups) > 1) {
                    echo '<br /><hr /><br /><h1>Planned future meetups...</h1>';
                }
            } else {
                echo $this->partial('layout::single-meetup-abbreviated', ['meetup' => $meetup]);
            }
            ?>
        <?php endforeach; ?>
    <?php else: ?>
    <strong>No meetups currently planned...</strong>
    <?php endif; ?>
</div>

<div class="wrapper content">
    <hr /><br />
    <h1>Previous meetups</h1>
    <?php foreach ($pastMeetups as $meetup): ?>
        <?= $this->partial('layout::single-meetup-abbreviated', ['meetup' => $meetup]); ?>
    <?php endforeach; ?>
</div>
