<?php
$title = "Meet the Team";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <ul id="team">
        <li>
            <img src="/images/team/james.png" />
            <h2>James Titcumb</h2>
            <p>James is the founder of the UK based PHP Hampshire user group and the PHP South Coast Conference. He's
                also a Zend Certified Engineer and consultant at Roave. During his downtime, he continues to run the PHP
                Hampshire user group and the conference, and keeps up with active contributions to various open source
                projects.</p>
            <p><a href="http://www.jamestitcumb.com/">jamestitcumb.com</a> | <a href="https://twitter.com/asgrim">@asgrim</a></p>
        </li>
        <li>
            <img src="/images/team/lee.png" />
            <h2>Lee Boynton</h2>
            <p>Lee is a "full stack" developer based in Portsmouth, UK who is always interested in experimenting with
               new technologies. This ranges from the latest PHP frameworks, to front-end JavaScript libraries and to
               Linux server management tools. Other interests include security, code quality and automation.</p>
            <p><a href="http://lboynton.com/">lboynton.com</a> | <a href="https://twitter.com/leeboynton">@leeboynton</a></p>
        </li>
        <li>
            <img src="/images/team/steve.jpg" />
            <h2>Steve Winter</h2>
            <p>Steve is a consultant developer based in Hampshire. We know he's a little bit crazy, because he cycled
                all the way from Beijing to Istanbul!</p>
            <p><a href="https://twitter.com/steveWinterNZ">@steveWinterNZ</a></p>
        </li>
    </ul>

</div>
