<?php
$title = "Meet the Team";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <ul id="team">
        <li>
            <img src="/images/team/lee.png"/>
            <h2>Lee Boynton</h2>
            <p>
                Lee is a "full stack" developer based in Portsmouth, UK who is always interested in experimenting with
                new technologies. This ranges from the latest PHP frameworks, to front-end JavaScript libraries and to
                Linux server management tools. Other interests include security, code quality and automation.
            </p>
            <p>
                <a href="https://twitter.com/leeboynton">@leeboynton</a>
            </p>
        </li>
        <li>
            <img src="/images/team/michal.jpg"/>
            <h2>Michal Skokowski</h2>
            <p>
                Michal is a Senior PHP Developer at Efficio, a developer who prefers backend development, but who isn't
                afraid to work with frontend systems either. Michal has been a part of the PHPHants family for a long
                time and a member of the organisation team since 2017.
            </p>
            <p>
                <a href="https://twitter.com/skoku87">@skoku87</a>
            </p>
        </li>
        <li>
            <img src="/images/team/joel.jpeg"/>
            <h2>Joel Jenvey</h2>
            <p>
                Programmer, engineer, sci-fi fan. Supporting #StargateNow #DriveToRevive Volunteer at @PHPhants
            </p>
            <p>
                <a href="https://twitter.com/jdjenvey">@jdjenvey</a>
            </p>
        </li>
    </ul>
</div>
