<?php
declare(strict_types=1);

/** @var \App\Entity\Talk[] $talksWithVideo */

$title = 'Videos';
$this->headTitle($title);

?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <ul id="videos">
    <?php foreach ($talksWithVideo as $talk): ?>
        <li>
            <h3 class="title"><?= $this->escapeHtml($talk->getTitle()); ?></h3>
            <h4 class="speaker">
                <span class="unbold">by</span>

                <?php

                if (null === $talk->getSpeaker()) {
                    echo "OMG";
                }


                ?>
                <?= $this->escapeHtml($talk->getSpeaker()->getFullName()); ?>
                <span class="unbold">on</span>
                <?= $this->escapeHtml($talk->getTime()->format('d F Y')); ?>
            </h4>
            <div class="lazyload-youtube" data-youtube-id="<?= $this->escapeHtmlAttr($talk->getYouTubeId()); ?>" data-ratio="16:9">
              <a href="https://youtu.be/<?= $this->escapeHtmlAttr($talk->getYouTubeId()); ?>">Watch on YouTube</a>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
