
<footer>
	<div class="fixed-width">
		<p>&copy; <?php echo date('Y'); ?> PHP Hampshire. All website source code available under <a href="http://opensource.org/licenses/MIT">MIT license</a> from <a href="https://github.com/phphants/phphants.github.io">PHPH Github</a>.</p>
		<nav><ul>
			<li><a href="https://github.com/phphants">GitHub</a></li>
			<li><a href="https://plus.google.com/100929948456763294967">Google+</a></li>
			<li><a href="https://twitter.com/phphants">Twitter</a></li>
			<li><a href="https://facebook.com/pughants">Facebook</a></li>
		</ul></nav>
	</div>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3367595-6', 'phphants.co.uk');
  ga('send', 'pageview');

</script>
