<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php echo $this->headTitle('PHP Hampshire')->setSeparator(' - ')->setAutoEscape(false) ?>

	<link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:300' rel='stylesheet' type='text/css'>
	<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/css/style.css'); ?>

	<?php echo $this->headScript(); ?>
</head>
<body>
<?php echo $this->partial('layout/header'); ?>

<?php echo $this->content; ?>

<?php echo $this->partial('layout/footer'); ?>

<?php echo $this->inlineScript() ?>
</body>
</html>
