<?php
$this->headTitle('Welcome!');
?>

<h1>Welcome to PHP Hampshire</h1>
<p>PHP Hampshire is a not-for-profit PHP and other community software (e.g. Linux, MySQL, Apache etc.) user group that focuses on hobbyist and professional software development.</p>
<p>If you would like to get involved in our community, please visit our <a href="https://groups.google.com/group/phphants">Google Group community</a>.</p>

<h2>Meetups</h2>
<a href="<?php echo $this->url('meetups'); ?>">See our meetups page</a>

<h2>Projects</h2>
<ul>
	<li><a href="https://github.com/phphants/phph-site">This website</a></li>
	<li><a href="http://www.godeploy.com/">GoDeploy</a>
</ul>