<?php
$this->headTitle('Welcome!');
?>

<h1>Welcome to PHP Hampshire</h1>
<p style="font-weight: bold;">PHP Hampshire is a PHP User Group whose aim is to share knowledge, learn new things and support the PHP community in Hampshire, UK.</p>
<p>If you would like to get involved in our community, please visit our <a href="https://groups.google.com/group/phphants">Google Group community</a>.</p>

<h2>Speakers</h2>
<p>We are looking for speakers for the summer meetup!</p>
<p>The slots we have are 10-15 minutes on PHP or related topics. If you would like to become a speaker at a future PHP Hampshire event, please get in touch with us by emailing <a href="mailto:info-at-phphants.co.uk">info-at-phphants.co.uk</a>.

<h2>Meetups</h2>
<a href="<?php echo $this->url('meetups'); ?>">See our meetups page</a>

<h2>Projects</h2>
<ul>
	<li><a href="https://github.com/phphants/phph-site">This website</a></li>
	<li><a href="http://www.godeploy.com/">GoDeploy</a>
</ul>

<h2>Support Us</h2>
<p>Support your local PHP user group in Hampshire by donating to help shape future events!</p>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="8Q4PUM75V8DGS">
<input type="image" src="https://www.paypalobjects.com/en_US/GB/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
