<?php
$title = "Join The Community";
$this->headTitle($title);
?>

<div class="fixed-width">
<div class="content">
    <h1><?php echo $title; ?></h1>
    <p>PHP Hampshire costs nothing to join, and you can have any level of involvement in the group. Obviously if you want to help out and get stuck in and help out, we'll be more than happy, but it is not a requirement!</p>

    <p>Our discussions take place on our <strong><a href="https://groups.google.com/group/phphants">Google Group community</a></strong> which is a discussion mailing list and forum.</p>

    <p>Please come and join us!</p>
    
    <a href="https://groups.google.com/group/phphants"><img src="/images/google-groups-logo.png" alt="Google Groups" /></a>
</div>
</div>