<?php
$title = "Videos";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <ul id="videos">
    <?php foreach ($videos as $video): ?>
        <li>
            <h3 class="title"><?php echo $video['title']; ?></h3>
            <h4 class="speaker"><span class="unbold">by</span> <?php echo $video['speaker']; ?> <span class="unbold">on</span> <?php echo $video['date']; ?></h4>
            <div class="lazyload-youtube" data-youtube-id="<?php echo $video['code']; ?>" data-ratio="16:9">
              <a href="https://youtu.be/<?php echo $video['code']; ?>">Watch on YouTube</a>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
