<?php
declare(strict_types = 1);

/** @var \App\Form\Account\ChangePasswordForm $form */
/** @var \Zend\View\Renderer\PhpRenderer $this */

$title = 'Change your password';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('password')); ?>

    <?= $this->formRow($form->get('confirmPassword')); ?>

    <?= $this->partial('partial::xkcd936'); ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?= $this->formRow($form->get('changePasswordForm_csrf')); ?>
    <?= $this->form()->closeTag(); ?>

</div>
