<?php
declare(strict_types = 1);

/** @var \App\Form\Account\ChangeProfileForm $form */
/** @var \Zend\View\Renderer\PhpRenderer $this */

$title = 'Change profile settings';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('name')); ?>

    <?= $this->formRow($form->get('email')->setAttributes([
        'placeholder' => 'foo@bar.com',
    ])); ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?= $this->formRow($form->get('changeProfileForm_csrf')); ?>
    <?= $this->form()->closeTag(); ?>

</div>
