<?php
$title = "Kiwi IRC Web Client Help";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->
	
<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>To log in and start chatting to other PHP Hampshire members, pick a nickname and click on "Start..." on the <a href="<?php echo $this->url('chat'); ?>">IRC web client</a>. If you need to know anything else, <a href="<?php echo $this->url('contact'); ?>">contact us</a>.</p>
    <p>You can learn more about IRC, and in particular the Freenode network pn the <a href="http://freenode.net/faq.shtml">Freenode, frequently asked questions</a> page.</p>
</div>
