<?php
$title = "Kiwi IRC Web Client";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->
	
<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>Need help with IRC? <a href="<?php echo $this->url('chat-help'); ?>" >Find out more...</a></p>

    <iframe src="https://kiwiirc.com/client/irc.freenode.net/?nick=guest|?#phph" style="border:0; width:100%; height:450px;"></iframe>
</div>
