<?php
$title = "Members";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <p><a href="<?php echo $this->url('member-register');?>" >Register</a></p>
    <ul class="members" >
    <?php foreach($members as $member):?>
        <li class="member">
            <?php echo $this->renderMember($member);?>
        </li>
    <?php endforeach;?>
    </ul>
</div>
