<?php
$title = "Registration pending";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>Thank you for registering as a member on PHP Hampshire. We have emailed you a link you need to click to verify your registration.</p>

    <p>If you experience any problems, please <a href="<?php echo $this->url('contact');?>">contact us</a> for assistance.</p>
</div>