<?php
$title = "Registration verified";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>Thank you for registering as a member on PHP Hampshire. </p>

    <p>
        We hope to see you at a meetup soon, until then, there are plenty of ways to get involved.
        Visit the <a href="<?php echo $this->url('contact');?>">contact page</a> for details on how to get in touch.
    </p>
</div>