<?php
$title = "Registration verification failed";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>
        Registration verification has failed. The link you have clicked is not recognised on our system.
    </p>

    <p>
        If you are experiencing problems with registration, please <a href="<?php echo $this->url('contact');?>" >contact us</a>.
    </p>
</div>