<?php
$title = "Contact PHP Hampshire";
$this->headTitle($title);
?>

<h1><?php echo $title; ?></h1>
<p>There are several ways to get in touch, but the best way is via our <a href="https://groups.google.com/group/phphants">Google Groups community</a>.</p>
<p>Alternatively you will find us...</p>
<ul>
    <li>on Twitter... <a href="https://twitter.com/phphants">@phphants</a></li>
    <li>on Facebook... <a href="http://www.facebook.com/pughants">PHP Hampshire</a></li>
    <li>by email... <a href="mailto:info-at-phphants.co.uk">info-at-phphants.co.uk</a>
</ul>
