<?php
$title = "Contact PHP Hampshire";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>There are several ways to get in touch.</p>
    <p>You can contact us...</p>
    <ul class="contact-links">
        <li>in the Google Groups community... <a href="https://groups.google.com/group/phphants">phphants</a></li>
        <li>on Twitter... <a href="https://twitter.com/phphants">@phphants</a></li>
        <li>on Facebook... <a href="http://www.facebook.com/pughants">PHP Hampshire</a></li>
        <li>via email... <a href="mailto:info@phphants.co.uk">info@phphants.co.uk</a></li>
        <li>and on IRC... <a href="<?php echo $this->url('chat'); ?>">using the IRC webclient</a> or #phph on freenode.</li>
    </ul>
</div>
