<?php
$title = "Proudly sponsored by...";
$this->headTitle($title);
?>

<h1><?php echo $title; ?></h1>

<div id="sponsors">
    <h2>Venue: Broad Oak Social Club</h2>
    <p>Broad Oak Sports & Social Club, Portsmouth is a lively and family friendly club of around 1,400 members.</p>
    <p>Visit: <a href="http://broadoaksocialclub.net/">broadaksocialclub.net</a></p>
    <br class="clear" />

    <h2>Sponsor: Ed Group</h2>
    <a href="http://www.ed.co.uk/" class="noborder align-right"><img src="/images/ed.png" alt="Ed Group" class="sponsor-logo" /></a>
    <p>Ed Group are a financial services company who run a successful life insurance broker Protected.co.uk.</p>
    <p>Visit: <a href="http://www.ed.co.uk/">www.ed.co.uk</a></p>
    <br class="clear" />

    <h2>Sponsor: You...?</h2>
    <p>If you would like to sponsor PHP Hampshire, please <a href="<?php echo $this->url('contact'); ?>">get in touch</a>.</p>
</div>