<?php
$title = "Proudly sponsored by...";
$this->headTitle($title);
?>

<h1><?php echo $title; ?></h1>

<div id="sponsors">
    <h2>Sponsor: Spectrum IT</h2>
	<a href="http://www.spectrumit.co.uk/" class="noborder align-right"><img src="/images/spectrum-it.png" alt="Spectrum IT" class="sponsor-logo" /></a>
	<p>Spectrum IT Recruitment is a collaboration of over 10 years recruitment experience, providing recruitment services and consultancy to the IT sector UK wide.</p>
    <p>Visit: <a href="http://www.spectrumit.co.uk/">www.spectrumit.co.uk</a></p>
    <br class="clear" />

    <h2>Sponsor: Protected.co.uk</h2>
    <a href="http://www.protected.co.uk/" class="noborder align-right"><img src="/images/protected.png" alt="Protected.co.uk" class="sponsor-logo" /></a>
    <p>Protected.co.uk is a life insurance comparison website which helps customers find the right policy for their needs.</p>
    <p>Visit: <a href="http://www.protected.co.uk/">www.protected.co.uk</a></p>
    <br class="clear" />

    <h2>Sponsor: Zend - The PHP Company</h2>
    <a href="http://www.zend.com/" class="noborder align-right"><img src="/images/zend.png" alt="Zend - the PHP company" class="sponsor-logo" /></a>
    <p>Zend is a company at the heart of PHP. They provide Zend Server, Zend Studio, provide training &amp; certification, contributions to Zend Framework and much more.</p>
    <p>Visit: <a href="http://www.zend.com/">www.zend.com</a></p>
    <br class="clear" />

    <h2>Sponsor: O'Reilly User Group Program</h2>
    <a href="http://www.oreilly.com/" class="noborder align-right"><img src="/images/oreilly-ug.gif" alt="O'Reilly" class="sponsor-logo" /></a>
    <p>PHP Hampshire is proud to be part of the O'Reilly User Group Program, which means our members can benefit from discounts (40% off printed books, 50% off e-books) and other goodies sometimes.</p>
    <p>Visit: <a href="http://www.oreilly.com/">www.oreilly.com</a></p>
    <br class="clear" />

    <h2>Sponsor: JetBrains PhpStorm</h2>
    <a href="http://www.jetbrains.com/phpstorm/" class="noborder align-right"><img src="/images/phpstorm.png" alt="JetBrains PhpStorm" class="sponsor-logo" /></a>
    <p>PhpStorm keeps up with latest PHP & web languages trends, integrates a variety of modern tools, and brings even more extensibility with support for major PHP frameworks.</p>
    <p>Visit: <a href="http://www.jetbrains.com/phpstorm/">www.jetbrains.com/phpstorm</a></p>
    <br class="clear" />

    <h2>Venue: Oasis Conference Centre</h2>
	<p>Visit: <a href="http://www.oasisthevenue.com/conference-centre">www.oasisthevenue.com/conference-centre</a></p>
	<br class="clear" />

    <h2>Sponsor: You...?</h2>
    <p>If you would like to sponsor PHP Hampshire, please <a href="<?php echo $this->url('contact'); ?>">get in touch</a>.</p>
</div>
