<?php
$title = "Proudly sponsored by...";
$this->headTitle($title);
?>

<h1><?php echo $title; ?></h1>

<div id="sponsors">
    <h2>Sponsor: Spectrum IT</h2>
	<a href="http://www.spectrumit.co.uk/" class="noborder align-right"><img src="/images/spectrum-it.png" alt="Spectrum IT" class="sponsor-logo" /></a>
	<p>Spectrum IT Recruitment is a collaboration of over 10 years recruitment experience, providing recruitment services and consultancy to the IT sector UK wide.</p>
    <p>Visit: <a href="http://www.spectrumit.co.uk/">www.spectrumit.co.uk</a></p>
    <br class="clear" />

    <h2>Sponsor: Protected.co.uk</h2>
    <a href="http://www.protected.co.uk/" class="noborder align-right"><img src="/images/protected.png" alt="Protected.co.uk" class="sponsor-logo" /></a>
    <p>Protected.co.uk is a life insurance comparison website which helps customers find the right policy for their needs.</p>
    <p>Visit: <a href="http://www.protected.co.uk/">www.protected.co.uk</a></p>
    <br class="clear" />

    <h2>Venue: Oasis Conference Centre</h2>
	<p>Visit: <a href="http://www.oasisthevenue.com/conference-centre">www.oasisthevenue.com/conference-centre</a></p>
	<br class="clear" />

    <h2>Sponsor: You...?</h2>
    <p>If you would like to sponsor PHP Hampshire, please <a href="<?php echo $this->url('contact'); ?>">get in touch</a>.</p>
</div>
