<?php $this->headTitle('Meetups'); ?>

</div><!-- end of gradient-wrapper -->

<?php
$first = true;
?>

<div class="wrapper content">
    <h1>Next Meetup<?php echo count($future_meetups) > 1 ? 's' : ''; ?>...</h1>

    <?php if (count($future_meetups) > 0): ?>
        <?php foreach ($future_meetups as $meetup): ?>
            <?php
            if ($first) {
                echo $this->renderMeetup()->full($meetup);
                $first = false;
                if (count($future_meetups) > 1) {
                    echo '<br /><hr /><br /><h1>Planned future meetups...</h1>';
                }
            } else {
                echo $this->renderMeetup()->short($meetup);
            }
            ?>
        <?php endforeach; ?>
    <?php else: ?>
    <strong>No meetups currently planned...</strong>
    <?php endif; ?>
</div>

<div class="wrapper content">
    <hr /><br />
    <h1>Previous meetups</h1>
    <?php foreach ($past_meetups as $meetup): ?>
        <?= $this->renderMeetup()->short($meetup); ?>
    <?php endforeach; ?>
</div>
