<?php $this->headTitle('Meetups'); ?>

<h1>Meetups</h1>
<h2>Next Meetup</h2>
<h3>15th December 2012</h3>
<ul>
	<li><strong>Time:</strong> Midday onwards (usually finish about 3pm)</li>
	<li><strong>Location:</strong> The Deco, Portsmouth</li>
	<li><strong>Topic of the Month:</strong> PHP!</li>
	<li><strong>Talking points</strong>
	<ul>
		<li>How can we spread the word of the group?</li>
		<li>Community - what do people think of the site? What improvements can we make?</li>
		<li>Popular frameworks - ZF2, Symfony2, Silex etc.</li>
		<li>Events</li>
		<li>Sponsorship</li>
	</ul>
</ul>