<?php $this->headTitle('Meetups'); ?>

<div class="content-wrapper">

<div class="wrapper">
<div class="content">
    <h1>Next Meetup<?php echo count($future_meetups) > 1 ? 's' : ''; ?>...</h1>

    <?php if (count($future_meetups) > 0): ?>
        <?php foreach ($future_meetups as $meetup): ?>
            <?php echo $this->renderMeetup($meetup); ?>
        <?php endforeach; ?>
    <?php else: ?>
    <strong>No meetups currently planned...</strong>
    <?php endif; ?>
</div>
</div>

</div>