<?php
declare(strict_types = 1);

$title = 'Account Dashboard';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <ul class="dashboard">
        <?php if ($this->user()->hasRole(\App\Service\Authorization\Role\AdministratorRole::NAME)): ?>
        <li class="meetups">
            <a href="<?= $this->escapeHtmlAttr($this->url('account-meetups-list')); ?>">
                <span>Meetups</span>
            </a>
        </li>
        <li class="locations">
            <a href="<?= $this->escapeHtmlAttr($this->url('account-locations-list')); ?>">
                <span>Locations</span>
            </a>
        </li>
        <li class="speakers">
            <a href="<?= $this->escapeHtmlAttr($this->url('account-speakers-list')); ?>">
                <span>Speakers</span>
            </a>
        </li>
        <?php endif; ?>
        <li class="logout">
            <a href="<?= $this->escapeHtmlAttr($this->url('account-logout')); ?>">
                <span>Logout</span>
            </a>
        </li>
    </ul>
</div>
