<?php
declare(strict_types = 1);

/** @var \App\Form\Account\LoginForm $form */

$title = 'Login';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('email')->setAttributes([
        'placeholder' => 'foo@bar.com',
    ])); ?>

    <?= $this->formRow($form->get('password')); ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?= $this->formRow($form->get('loginForm_csrf')); ?>
    <?= $this->form()->closeTag(); ?>

</div>
