<?php
declare(strict_types = 1);

/** @var string|null $error */

$title = 'Login';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?php
    if (null !== $error) {
        echo '<span class="error">' . $this->escapeHtml($error) . '</span>';
    }
    ?>

    <form method="POST">
        <label>
            Email:
            <input type="text" name="email" placeholder="foo@bar.com" />
        </label>

        <label>
            Password:
            <input type="password" name="password" placeholder="******" />
        </label>

        <input type="submit" value="Login" />
    </form>
</div>
