<?php
declare(strict_types = 1);

/** @var \App\Form\Account\LoginForm $form */

$title = 'Login';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('email')->setAttributes([
        'placeholder' => 'foo@bar.com',
    ])); ?>

    <?= $this->formRow($form->get('password')); ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?= $this->formRow($form->get('loginForm_csrf')); ?>
    <?= $this->form()->closeTag(); ?>

    <br />

    <h1>Or log in using...</h1>

    <ul class="login-with">
        <?php foreach (\App\Entity\UserThirdPartyAuthentication\UserThirdPartyAuthentication::kinds() as $kind): ?>
            <?php
            /** @var \App\Entity\UserThirdPartyAuthentication\UserThirdPartyAuthentication $kind */
            $route = $kind::routeNameForAuthentication();
            $name = $kind::type();
            $nameLowercase = strtolower($name);
            ?>
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url($route)); ?>" class="btn btn-block btn-social btn-<?= $this->escapeHtmlAttr($nameLowercase); ?>">
                    <span class="fa fa-<?= $this->escapeHtmlAttr($nameLowercase); ?>"></span> Sign in with <?= $this->escapeHtml($name); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <h1>If you don't have an account...</h1>

    <p>You can <a href="<?= $this->escapeHtmlAttr($this->url('account-register')); ?>">register now</a> with your email.</p>

</div>
