<?php
declare(strict_types = 1);

/** @var \App\Form\Account\RegisterForm $form */
/** @var \Zend\View\Renderer\PhpRenderer $this */

$this->headScript()->appendFile('https://www.google.com/recaptcha/api.js');

$title = 'Register';
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->formRow($form->get('email')->setAttributes([
        'placeholder' => 'foo@bar.com',
    ])); ?>

    <?= $this->formRow($form->get('password')); ?>

    <?= $this->formRow($form->get('confirmPassword')); ?>

    <br />
    <div class="g-recaptcha" data-sitekey="<?= $this->escapeHtmlAttr($form->get('g-recaptcha-response')->getAttribute('recaptchaPublicKey')); ?>"></div>
    <?= $this->formElementErrors($form->get('g-recaptcha-response')); ?>

    <?= $this->formRow($form->get('submit')); ?>

    <?= $this->formRow($form->get('registerForm_csrf')); ?>
    <?= $this->form()->closeTag(); ?>

</div>
