<?php
declare(strict_types = 1);

/** @var \App\Form\Account\MeetupForm $form */

$title = 'Add a new meetup';
$this->headTitle($title);
$form->prepare();
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?php echo $title; ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?= $this->form($form); ?>

    <?= $this->form()->closeTag(); ?>

    <button onclick="return addTalk()">Add another talk</button>

</div>

<script type="text/javascript">
    function addTalk() {
        var currentCount = $('form > fieldset.talks-collection > fieldset').length;
        var template = $('form > fieldset.talks-collection > span').data('template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset.talks-collection').append(template);

        return false;
    }
</script>
