<?php
declare(strict_types=1);

$this->headTitle('Meetups');

/** @var \App\Entity\Meetup $meetup */
/** @var \App\Entity\User $winner */
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1>Meetup Winner : </h1>

    <a href="<?= $this->escapeHtmlAttr($this->url('account-meetup-view', ['uuid' => $meetup->getId()])); ?>" class="link-button">Back to meetup</a>
    <a href="<?= $this->escapeHtmlAttr($this->url('account-meetup-pick-a-winner', ['meetup' => $meetup->getId()])); ?>" class="link-button">Pick another winner</a>

    <h2>The winner is: <?= $this->escapeHtml($winner->displayName()); ?></h2>
</div>
