<?php
declare(strict_types=1);

$this->headTitle('Meetups');

/** @var \App\Entity\Meetup $meetup */
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1>View Meetup : </h1>

    <a href="<?= $this->url('account-meetups-list'); ?>" class="link-button">Back to meetups list</a>
    <a href="<?= $this->url('account-meetup-edit', ['uuid' => $meetup->getId()]); ?>" class="link-button">Edit this meetup</a>

    <table>
        <tbody>
            <tr>
                <td class="label">Start Date &amp; Time</td>
                <td><?= $meetup->getFromDate()->format('d F Y \a\t H:i'); ?></td>
            </tr>
            <tr>
                <td class="label">End Date &amp; Time</td>
                <td><?= $meetup->getToDate()->format('d F Y \a\t H:i'); ?></td>
            </tr>
            <tr>
                <td class="label">Location</td>
                <td><?= $this->escapeHtml($meetup->getLocation()->getName()); ?></td>
            </tr>
            <tr>
                <td class="label">Topic</td>
                <td><?= $this->escapeHtml(null !== $meetup->getTopic() ? $meetup->getTopic() : 'n/a'); ?></td>
            </tr>
            <tr>
                <td class="label">Eventbrite Link</td>
                <td>
                    <?php if (null !== $meetup->getEventbriteData()): ?>
                        <a href="<?= $this->escapeHtmlAttr($meetup->getEventbriteData()->getUrl()); ?>">
                            <?= $this->escapeHtml($meetup->getEventbriteData()->getEventbriteId()); ?>
                        </a>
                    <?php else: ?>
                        Not set (create Eventbrite link)
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>

    <br />

    <h3>Talks</h3>
    <br />

    <a href="<?= $this->url('account-talk-add', ['meetup' => $meetup->getId()]); ?>" class="link-button">Add a Talk</a>

    <table>
        <thead>
            <tr>
                <td>Speaker</td>
                <td>Time</td>
                <td>Title &amp; Abstract</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($meetup->getTalks() as $talk): ?>
            <tr>
                <td class="nowrap">
                <?php if (null !== $talk->getSpeaker()): ?>
                    <?= $this->escapeHtml($talk->getSpeaker()->getFullName()); ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
                </td>
                <td>
                    <?= $talk->getTime()->format('H:i'); ?>
                </td>
                <td>
                    <h4><?= $this->escapeHtml($talk->getTitle()); ?></h4>
                    <?= $this->escapeHtml($talk->getAbstract()); ?>
                </td>
                <td class="nowrap">
                    <a href="<?= $this->url('account-talk-edit', ['uuid' => $talk->getId()]); ?>" class="link-button tiny">Edit</a>
                    <a href="#" class="link-button tiny">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
