<?php
declare(strict_types=1);

$this->headTitle('Meetups');

/** @var \App\Entity\Meetup $meetup */
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1>View Meetup : </h1>

    <p><a href="<?= $this->url('account-meetup-edit', ['uuid' => $meetup->getId()]); ?>">Edit this meetup</a></p>

    <?= $this->partial('layout::single-meetup-full', ['meetup' => $meetup]); ?>
</div>
