<?php
declare(strict_types = 1);

/** @var \App\Entity\Meetup $meetup */

if ($this->user()->isAttendee()) {
    /** @var \App\Entity\User $user */
    $user = $this->user()->get();

    $isPast = $meetup->isBefore(new \DateTimeImmutable());
    $isAttending = $user->isAttending($meetup);

    if ($isAttending) {
        $label = $isPast ? 'I went to this' : 'I will be there';
    } else {
        $label = $isPast ? 'I wasn\'t there' : 'I won\'t be there';
    }

    ?>
    <a
        href="<?= $this->escapeHtmlAttr($this->url('account-meetup-toggle-attendance', ['uuid' => $meetup->getId()])); ?>"
        class="attending-button <?= $isAttending ? 'is-attending' : ''; ?>"
    >
        <?= $label; ?>
    </a>
    <?php
}
