<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="zCcrDBa7vaY6VybmNJlicAF1M4cD7EAGGiHLWc1zul4" />
    <?= $this->headTitle('PHP Hampshire')->setSeparator(' - ')->setAutoEscape(false) ?>

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,600,800|Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>
    <?= $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/style.css')
        ->appendStylesheet($this->basePath() . '/css/admin.css')
    ; ?>

    <?= $this->headScript(); ?>
</head>
<body>
<?= $this->partial('layout::header'); ?>

<?= $this->content; ?>

<?= $this->partial('layout::footer'); ?>

<?= $this->inlineScript() ?>
</body>
</html>
