<?php
declare(strict_types=1);

/** @var string $eventId */
/** @var string $eventTitle */
?>
<div style="width:100%; text-align:left; padding-top: 20px" >
    <iframe  src="https://www.eventbrite.co.uk/tickets-external?eid=<?= $this->escapeHtmlAttr($eventId); ?>&ref=etckt&v=2" frameborder="0" height="240" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe>
    <div style="font-family:Helvetica, Arial, sans-serif; font-size:10px; padding:5px 0 5px; margin:2px; width:100%; text-align:left;" >
        <a style="color:#888; text-decoration:none;" target="_blank" href="https://www.eventbrite.co.uk/r/etckt">Event Registration Online</a>
        <span style="color:#888888;"> for </span>
        <a style="color:#888; text-decoration:none;" target="_blank" href="https://www.eventbrite.co.uk/event/<?= $this->escapeHtmlAttr($eventId); ?>?ref=etckt"><?= $this->escapeHtml($eventTitle); ?></a>
        <span style="color:#888;"> powered by </span>
        <a style="color:#888; text-decoration:none;" target="_blank" href="https://www.eventbrite.co.uk?ref=etckt">Eventbrite</a>
    </div>
</div>
