<footer>
    <div class="wrapper">
        <ul class="links">
            <li><a href="https://github.com/phphants">GitHub</a></li>
            <li><a href="https://plus.google.com/100929948456763294967">Google+</a></li>
            <li><a href="https://twitter.com/phphants">Twitter</a></li>
            <li><a href="https://facebook.com/pughants">Facebook</a></li>
            <li><a href="<?= $this->escapeHtmlAttr($this->url('chat')); ?>">IRC</a></li>
        </ul>
        <p class="details">
            <a href="<?= $this->escapeHtmlAttr($this->url('code-of-conduct')); ?>" >Code of Conduct</a>
            | <a href="<?= $this->escapeHtmlAttr($this->url('team')); ?>" >The Team</a>
            | <a href="<?= $this->escapeHtmlAttr($this->url('account-dashboard')); ?>">&#128274;</a>
        </p>
        <p class="details">&copy; <?php echo date('Y'); ?> PHP Hampshire CIC. All website source code available under <a href="http://opensource.org/licenses/MIT">MIT license</a> from <a href="https://github.com/phphants/phph-site">PHP Hampshire GitHub</a>.</p>
        <p class="details">PHP Hampshire CIC is registered in England and Wales, company number 09312297. VAT registered, number 226 583 594</p>
    </div>
</footer>

<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="/js/scripts.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-3367595-6', 'phphants.co.uk');
  ga('send', 'pageview');

</script>
