<?php
declare(strict_types=1);
?>

<div class="gradient-wrapper">

<header>
<div class="wrapper">
    <a href="<?= $this->url('home'); ?>" class="header-logo"><h1 >PHP Hampshire</h1></a>
    <a class="nav-button" href="#">Menu</a>
    <nav>
        <ul class="navigation">
            <li>
                <a href="<?= $this->url('home'); ?>">Home</a>
            </li>
            <li>
                <a href="<?= $this->url('meetups'); ?>">Meetups</a>
            </li>
            <li>
                <a href="<?= $this->url('videos'); ?>">Videos</a>
            </li>
            <li>
                <a href="<?= $this->url('sponsors'); ?>">Sponsors</a>
            </li>
            <li>
                <a href="<?= $this->url('contact'); ?>">Contact</a>
            </li>
        </ul>
    </nav>
</div>
</header>

<?php if ($this->user()->isLoggedIn()): ?>
    <nav class="admin"><div class="wrapper">
        <ul>
            <li>
                <a href="<?= $this->url('account-dashboard'); ?>">Dashboard</a>
            </li>
            <li>
                <a href="<?= $this->url('account-meetups-list'); ?>">Meetups</a>
            </li>
            <li>
                <a href="<?= $this->url('account-locations-list'); ?>">Locations</a>
            </li>
            <li>
                <a href="<?= $this->url('account-logout'); ?>">Logout</a>
            </li>
        </ul>
    </div></nav>
<?php endif; ?>
