<?php
declare(strict_types=1);
?>

<div class="gradient-wrapper">

<header>
<div class="wrapper">
    <a href="<?= $this->url('home'); ?>" class="header-logo"><h1 >PHP Hampshire</h1></a>
    <a class="nav-button" href="#">Menu</a>
    <nav>
        <ul class="navigation">
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url('home')); ?>">Home</a>
            </li>
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url('meetups')); ?>">Meetups</a>
            </li>
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url('videos')); ?>">Videos</a>
            </li>
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url('sponsors')); ?>">Sponsors</a>
            </li>
            <li>
                <a href="<?= $this->escapeHtmlAttr($this->url('contact')); ?>">Contact</a>
            </li>
        </ul>
        <div class="pull-right login-status-text">
            <?php if ($this->user()->isLoggedIn()): ?>
                Logged in as <?= $this->user()->get()->displayName(); ?>. View your <a href="<?= $this->escapeHtmlAttr($this->url('account-dashboard')); ?>">Dashboard</a>.
                </li>
            <?php else: ?>
                <a href="<?= $this->escapeHtmlAttr($this->url('account-login')); ?>">Login</a> now to register your attendance.
            <?php endif; ?>
        </div>
    </nav>
</div>
</header>
