<?php
declare(strict_types = 1);

/** @var \App\Entity\Meetup $meetup */

/** @var \App\Entity\Talk[]|\Doctrine\Common\Collections\Collection $abbreviatedTalks */
$abbreviatedTalks = $meetup->getAbbreviatedTalks();
?>

<h2><?= $meetup->getFromDate()->format('jS F Y'); ?> <?= $this->partial('layout::attending-button', ['meetup' => $meetup]); ?></h2>

<?php if (count($abbreviatedTalks) > 0): ?>
<ul class="meetup-details">
    <li>
        <strong>Talk<?= count($abbreviatedTalks) === 1 ? '' : 's'; ?>:</strong>
        <ul class="talks">
        <?php foreach ($abbreviatedTalks as $talk): ?>
            <li>
                <?= $this->escapeHtml($talk->getTitle()); ?>
                    &mdash; <em>(by <strong><?= $this->twitterLinkOrName($talk->getSpeaker()); ?></strong>)</em>
            </li>
        <?php endforeach; ?>
        </ul>
    </li>
</ul>
<?php endif; ?>
