<?php
declare(strict_types = 1);

/** @var \App\Form\Account\SpeakerForm $form */
/** @var \App\Entity\Speaker|null $speaker */
/** @var string $title */

$this->headTitle($title);
$form->prepare();
?>

</div><!-- end of gradient-wrapper -->

<div class="wrapper content">
    <h1><?= $this->escapeHtml($title); ?></h1>

    <?= $this->form()->openTag($form); ?>

    <?php if (null !== $speaker && null !== $speaker->getImageFilename()): ?>
        <img src="<?= $this->escapeHtmlAttr($this->speakerHeadshot($speaker->getImageFilename())); ?>" class="full-speaker-headshot" />
    <?php endif; ?>

    <?= $this->form($form); ?>

    <?= $this->form()->closeTag(); ?>

</div>
