<?php
$title = "Code of Conduct";
$this->headTitle($title);
?>

</div><!-- end of gradient-wrapper -->
	
<div class="wrapper content">
    <h1><?php echo $title; ?></h1>
    <p>PHP Hampshire is a community driven PHP User Group, run by volunteers. It is for anyone wishing to learn PHP and related technologies, share knowledge and promote the PHP community in Hampshire.</p>
    <p>To achieve this, PHP Hampshire provide communication channels such as <a href="https://groups.google.com/group/phphants" >Google Groups</a>, <a href="https://github.com/phphants" >Github</a>, IRC channel (#phph on Freenode), <a href="https://twitter.com/phphants" >Twitter</a>, <a href="https://www.facebook.com/pughants">Facebook</a>, monthly meetups and social events.</p>
    <p>Communication can be informal and chatty but should be appropriate for a professional audience.  These channels are open to everyone, regardless of education, experience, age, gender, sexual orientation, disability, physical appearance, race, or religion.</p>
    <p><strong>No one is to be excluded nor made to feel they are excluded.</strong></p>

    <h2>General Rules</h2>
    <p>We expect you to:</p>
    <p>
        <ul>
            <li>Behave professionally.</li>
            <li>Share and be nice.</li>
            <li>Not insult or put down others experience or ability.</li>
            <li>Be respectful to others.</li>
        </ul>
    </p>
    <p>And these zero-tolerance rules are absolutely hard and fast:</p>
    <p>
        <ul>
            <li>Sexual language and imagery is not appropriate.</li>
            <li>Sexist, racist or exclusionary jokes are not appropriate.</li>
        </ul>
    </p>

    <h2>Complaints</h2>
    <p>You can contact the organisers at <a href="mailto:info@phphants.co.uk">info@phphants.co.uk</a>, send a direct message to <a href="https://twitter.com/phphants" >@phphants</a> on twitter or speak to an organiser, in person, at an event.</p>
    <p>The current organisers are:
        <ul>
            <li>James Titcumb (<a href="https://twitter.com/asgrim" >@asgrim</a>)</li>
            <li>Simon Wade (<a href="https://twitter.com/swade61" >@swade61</a>)</li>
            <li>Richard Holloway (<a href="https://twitter.com/richardjh_org" >@richardjh_org</a>)</li>
            <li>Lee Boynton (<a href="https://twitter.com/leeboynton" >@leeboynton</a>)</li>
        </ul>
    </p>
    <p>If you have a complaint that involves an organiser, you can contact one of the others in confidence. The group is the priority and steps will be taken to ensure the group is successful.</p>
    <p>PHP Hampshire is part of a larger community of PHP User Groups, around the world. If you feel your complaint requires external arbitration, let one of the organisers know and we can discuss the issue with the organisers of those User Groups.</p>

    <h2>Amendments</h2>
    <p>PHP Hampshire is a community effort. If you have suggestions on ways it can improve, including changes to this code of conduct, please <a href="mailto:info@phphants.co.uk" >let us know</a>.</p>
</div>
